# Generated by Django 3.0.5 on 2020-05-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpostmodel',
            table=None,
        ),
    ]
