# Generated by Django 3.0.5 on 2020-05-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200501_2219'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpostmodel',
            table='blog',
        ),
    ]
