# Generated by Django 3.0.5 on 2020-05-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200501_2220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpostmodel',
            table=None,
        ),
    ]
